// scripts/seedMedicines.js
// Run with: node scripts/seedMedicines.js

import mongoose from "mongoose";
import dotenv from "dotenv";
dotenv.config();

import Medicine from "../models/Medicine.js";

const medicines = [
  {
    name: "Panadol", brand: "GSK", generic: "Paracetamol", category: "painkiller",
    description: "Used to relieve mild to moderate pain and reduce fever. Commonly used for headaches, toothaches, and cold symptoms.",
    dosage: "500mg every 4-6 hours", price: 30, stock: 500,
    dosageGuide: { adult: "500mg-1g every 4-6 hours (max 4g/day)", child: "10-15mg/kg every 4-6 hours", elderly: "500mg every 6 hours", notes: "Do not exceed 8 tablets in 24 hours" },
    sideEffects: ["Nausea", "Rash", "Liver damage (overdose)"],
    longTermEffects: ["Liver toxicity", "Kidney damage with prolonged use"],
    contraindications: ["Severe liver disease", "Alcohol dependency"],
    foodInteractions: ["Avoid alcohol", "Avoid with other paracetamol-containing products"],
    drugInteractions: ["Warfarin", "Carbamazepine", "Isoniazid"],
    warnings: ["Do not exceed recommended dose", "Keep away from children"],
    whoShouldNotTake: ["Severe liver disease patients", "People with alcohol dependency"],
    foodTiming: "Can be taken with or without food",
    pregnancyWarning: "Generally considered safe during pregnancy at recommended doses. Consult doctor.",
    breastfeedingWarning: "Safe to use while breastfeeding at normal doses.",
    requiresPrescription: false, isCommonlyMisused: true, isApproved: true,
    safeAlternatives: ["Brufen", "Disprin"],
    aiExplanation: "Panadol contains Paracetamol and is used for pain relief and fever. It is safe when taken correctly but can damage the liver if too much is taken.",
    isEnriched: true,
  },
  {
    name: "Brufen", brand: "Abbott", generic: "Ibuprofen", category: "painkiller",
    description: "Anti-inflammatory painkiller used for pain, fever, and inflammation including arthritis, menstrual pain, and dental pain.",
    dosage: "400mg every 6-8 hours", price: 45, stock: 400,
    dosageGuide: { adult: "400-800mg every 6-8 hours", child: "5-10mg/kg every 6-8 hours", elderly: "Use lowest effective dose", notes: "Always take with food or milk" },
    sideEffects: ["Stomach upset", "Nausea", "Dizziness", "Heartburn"],
    longTermEffects: ["Stomach ulcers", "Kidney damage", "Cardiovascular risk"],
    contraindications: ["Peptic ulcer", "Severe kidney disease", "Heart failure", "Asthma triggered by NSAIDs"],
    foodInteractions: ["Avoid alcohol", "Take with food to prevent stomach upset"],
    drugInteractions: ["Aspirin", "Warfarin", "ACE inhibitors", "Lithium"],
    warnings: ["Take with food", "Avoid in last trimester of pregnancy"],
    whoShouldNotTake: ["Stomach ulcer patients", "Kidney disease patients", "Asthma patients"],
    foodTiming: "Must be taken with food or milk to protect stomach",
    pregnancyWarning: "Avoid in third trimester. Use with caution in first and second trimester.",
    breastfeedingWarning: "Small amounts pass into breast milk. Use with caution.",
    requiresPrescription: false, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Panadol", "Cataflam"],
    aiExplanation: "Brufen contains Ibuprofen and reduces pain and inflammation. Always take with food to protect your stomach. Avoid if you have stomach problems.",
    isEnriched: true,
  },
  {
    name: "Augmentin", brand: "GSK", generic: "Amoxicillin/Clavulanate", category: "antibiotic",
    description: "Broad-spectrum antibiotic used for bacterial infections including respiratory, urinary tract, skin and ear infections.",
    dosage: "625mg twice daily", price: 180, stock: 300,
    dosageGuide: { adult: "625mg every 12 hours for 5-7 days", child: "25mg/kg/day in divided doses", elderly: "Same as adult, monitor kidney function", notes: "Complete full course even if feeling better" },
    sideEffects: ["Diarrhea", "Nausea", "Vomiting", "Skin rash", "Yeast infection"],
    longTermEffects: ["Antibiotic resistance", "Gut flora disruption"],
    contraindications: ["Penicillin allergy", "Severe liver disease", "Previous jaundice with amoxicillin"],
    foodInteractions: ["Take with food to reduce stomach upset", "Avoid alcohol"],
    drugInteractions: ["Warfarin", "Methotrexate", "Oral contraceptives"],
    warnings: ["Complete full course", "Do not use for viral infections", "Tell doctor if allergic to penicillin"],
    whoShouldNotTake: ["Penicillin allergy patients", "Severe liver disease patients"],
    foodTiming: "Take at the start of a meal to reduce stomach side effects",
    pregnancyWarning: "Can be used during pregnancy when clearly needed. Consult doctor.",
    breastfeedingWarning: "Small amounts pass into breast milk. Generally safe.",
    requiresPrescription: true, isCommonlyMisused: true, isApproved: true,
    safeAlternatives: ["Azithromycin", "Clarithromycin"],
    aiExplanation: "Augmentin is an antibiotic that kills bacteria. Never take it without a doctor's prescription. Always complete the full course to prevent antibiotic resistance.",
    isEnriched: true,
  },
  {
    name: "Flagyl", brand: "Sanofi", generic: "Metronidazole", category: "antibiotic",
    description: "Antibiotic and antiprotozoal medicine used for bacterial and parasitic infections, especially gut infections and dental infections.",
    dosage: "400mg three times daily", price: 60, stock: 350,
    dosageGuide: { adult: "400mg three times daily for 5-7 days", child: "7.5mg/kg three times daily", elderly: "Same as adult", notes: "Take with food" },
    sideEffects: ["Nausea", "Metallic taste", "Headache", "Dizziness", "Dark urine"],
    longTermEffects: ["Nerve damage with prolonged use", "Peripheral neuropathy"],
    contraindications: ["First trimester of pregnancy", "History of blood disorders"],
    foodInteractions: ["Never take with alcohol — causes severe reaction", "Take with food"],
    drugInteractions: ["Alcohol (DANGEROUS)", "Warfarin", "Lithium", "Disulfiram"],
    warnings: ["NEVER drink alcohol while taking Flagyl", "May cause dark urine — normal"],
    whoShouldNotTake: ["First trimester pregnant women", "Alcohol consumers"],
    foodTiming: "Take with food or milk to reduce nausea",
    pregnancyWarning: "Avoid in first trimester. Can be used in second and third trimester if necessary.",
    breastfeedingWarning: "Avoid breastfeeding during treatment and for 24 hours after last dose.",
    requiresPrescription: true, isCommonlyMisused: true, isApproved: true,
    safeAlternatives: ["Tinidazole"],
    aiExplanation: "Flagyl kills bacteria and parasites in your gut. Never drink alcohol while taking it as it causes severe nausea and vomiting. Complete the full course.",
    isEnriched: true,
  },
  {
    name: "Omeprazole", brand: "Various", generic: "Omeprazole", category: "antacid",
    description: "Proton pump inhibitor used to reduce stomach acid. Treats acid reflux, peptic ulcers, and GERD.",
    dosage: "20mg once daily before breakfast", price: 80, stock: 400,
    dosageGuide: { adult: "20-40mg once daily", child: "0.5-1mg/kg once daily", elderly: "Same as adult", notes: "Take 30 minutes before breakfast" },
    sideEffects: ["Headache", "Diarrhea", "Nausea", "Stomach pain"],
    longTermEffects: ["Magnesium deficiency", "Vitamin B12 deficiency", "Bone fractures", "Increased infection risk"],
    contraindications: ["Known hypersensitivity to omeprazole"],
    foodInteractions: ["Take before meals for best effect"],
    drugInteractions: ["Clopidogrel", "Methotrexate", "Digoxin", "HIV medicines"],
    warnings: ["Do not use long-term without medical supervision", "May mask symptoms of stomach cancer"],
    whoShouldNotTake: ["Patients on clopidogrel (reduces its effectiveness)"],
    foodTiming: "Take 30 minutes before breakfast on empty stomach",
    pregnancyWarning: "Use with caution. Only if benefit outweighs risk.",
    breastfeedingWarning: "Avoid if possible. Small amounts pass into breast milk.",
    requiresPrescription: false, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Pantoprazole", "Ranitidine"],
    aiExplanation: "Omeprazole reduces the acid in your stomach and helps heal ulcers. Take it 30 minutes before breakfast. Don't use for more than 2 weeks without doctor advice.",
    isEnriched: true,
  },
  {
    name: "Amoxicillin", brand: "Various", generic: "Amoxicillin", category: "antibiotic",
    description: "Penicillin-type antibiotic used to treat bacterial infections of ear, nose, throat, skin, and urinary tract.",
    dosage: "500mg three times daily", price: 90, stock: 300,
    dosageGuide: { adult: "500mg every 8 hours", child: "25mg/kg/day in 3 divided doses", elderly: "Same as adult", notes: "Complete full 7-day course" },
    sideEffects: ["Diarrhea", "Nausea", "Rash", "Allergic reaction"],
    longTermEffects: ["Antibiotic resistance", "C. difficile infection"],
    contraindications: ["Penicillin allergy", "Mononucleosis"],
    foodInteractions: ["Can be taken with or without food"],
    drugInteractions: ["Warfarin", "Methotrexate", "Oral contraceptives"],
    warnings: ["Check for penicillin allergy before use", "Complete full course"],
    whoShouldNotTake: ["Penicillin allergic patients"],
    foodTiming: "Can be taken with or without food",
    pregnancyWarning: "Generally safe during pregnancy. Consult doctor.",
    breastfeedingWarning: "Safe during breastfeeding.",
    requiresPrescription: true, isCommonlyMisused: true, isApproved: true,
    safeAlternatives: ["Azithromycin", "Clarithromycin"],
    aiExplanation: "Amoxicillin is a common antibiotic for bacterial infections. Never take without prescription. Always complete full course to prevent antibiotic resistance.",
    isEnriched: true,
  },
  {
    name: "Disprin", brand: "Reckitt", generic: "Aspirin", category: "painkiller",
    description: "Pain reliever and fever reducer. Also used in low doses to prevent blood clots and heart attacks.",
    dosage: "300-600mg every 4-6 hours", price: 20, stock: 600,
    dosageGuide: { adult: "300-900mg every 4-6 hours", child: "Not recommended under 16", elderly: "75-150mg daily for heart protection", notes: "Take with food or water" },
    sideEffects: ["Stomach irritation", "Nausea", "Bleeding risk", "Tinnitus"],
    longTermEffects: ["Stomach ulcers", "Bleeding disorders", "Reye syndrome in children"],
    contraindications: ["Children under 16", "Peptic ulcer", "Bleeding disorders", "Asthma"],
    foodInteractions: ["Avoid alcohol", "Take with food"],
    drugInteractions: ["Warfarin", "Ibuprofen", "ACE inhibitors", "Methotrexate"],
    warnings: ["Never give to children under 16", "Increases bleeding risk"],
    whoShouldNotTake: ["Children under 16", "Stomach ulcer patients", "Bleeding disorder patients"],
    foodTiming: "Take with food or a full glass of water",
    pregnancyWarning: "Avoid in third trimester. Low dose may be used in first trimester under supervision.",
    breastfeedingWarning: "Avoid during breastfeeding.",
    requiresPrescription: false, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Panadol", "Brufen"],
    aiExplanation: "Disprin contains Aspirin for pain and fever. Never give to children under 16. In low dose it protects the heart — only use for this purpose under doctor supervision.",
    isEnriched: true,
  },
  {
    name: "Ciprofloxacin", brand: "Various", generic: "Ciprofloxacin", category: "antibiotic",
    description: "Fluoroquinolone antibiotic used for urinary tract infections, respiratory infections, and typhoid fever.",
    dosage: "500mg twice daily", price: 120, stock: 250,
    dosageGuide: { adult: "500mg every 12 hours for 7-14 days", child: "Not recommended under 18 except in special cases", elderly: "Reduce dose if kidney impairment", notes: "Drink plenty of water" },
    sideEffects: ["Nausea", "Diarrhea", "Headache", "Dizziness", "Tendon problems"],
    longTermEffects: ["Tendon rupture", "Peripheral neuropathy", "Antibiotic resistance"],
    contraindications: ["Children under 18", "Tendon disorders", "Epilepsy"],
    foodInteractions: ["Avoid dairy products and calcium supplements within 2 hours", "Avoid antacids"],
    drugInteractions: ["Antacids", "Warfarin", "Theophylline", "NSAIDs"],
    warnings: ["Avoid in children", "Report tendon pain immediately", "May cause dizziness"],
    whoShouldNotTake: ["Children under 18", "Patients with tendon problems", "Epilepsy patients"],
    foodTiming: "Take 2 hours before or 6 hours after dairy products or antacids",
    pregnancyWarning: "Avoid during pregnancy. Use only if no alternative.",
    breastfeedingWarning: "Avoid during breastfeeding.",
    requiresPrescription: true, isCommonlyMisused: true, isApproved: true,
    safeAlternatives: ["Amoxicillin", "Azithromycin"],
    aiExplanation: "Ciprofloxacin is a strong antibiotic for serious infections. Never take without prescription. Avoid dairy products when taking it as they reduce its effectiveness.",
    isEnriched: true,
  },
  {
    name: "Metformin", brand: "Various", generic: "Metformin", category: "diabetes",
    description: "First-line medication for type 2 diabetes. Helps control blood sugar levels by reducing glucose production in the liver.",
    dosage: "500mg twice daily with meals", price: 50, stock: 400,
    dosageGuide: { adult: "500mg twice daily, increase gradually to 2000mg/day", child: "10 years and older: 500mg twice daily", elderly: "Use with caution, monitor kidney function", notes: "Always take with meals" },
    sideEffects: ["Nausea", "Diarrhea", "Stomach upset", "Metallic taste"],
    longTermEffects: ["Vitamin B12 deficiency", "Lactic acidosis (rare)"],
    contraindications: ["Kidney disease", "Liver disease", "Heart failure", "Before surgery or contrast dye procedures"],
    foodInteractions: ["Take with meals to reduce stomach side effects", "Avoid excessive alcohol"],
    drugInteractions: ["Contrast dyes (stop before procedures)", "Alcohol", "Certain diuretics"],
    warnings: ["Stop before any surgery or contrast procedures", "Monitor kidney function regularly"],
    whoShouldNotTake: ["Kidney disease patients", "Liver disease patients", "Heart failure patients"],
    foodTiming: "Take with meals — never on empty stomach",
    pregnancyWarning: "Not recommended during pregnancy. Insulin is preferred.",
    breastfeedingWarning: "Small amounts pass into breast milk. Consult doctor.",
    requiresPrescription: true, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Glipizide", "Sitagliptin"],
    aiExplanation: "Metformin controls blood sugar in diabetes. Always take with food to avoid stomach problems. Never stop without doctor advice.",
    isEnriched: true,
  },
  {
    name: "Amlodipine", brand: "Various", generic: "Amlodipine", category: "cardiovascular",
    description: "Calcium channel blocker used to treat high blood pressure and chest pain (angina).",
    dosage: "5mg once daily", price: 70, stock: 300,
    dosageGuide: { adult: "5-10mg once daily", child: "2.5-5mg once daily (6-17 years)", elderly: "Start with 2.5mg daily", notes: "Can be taken at any time of day" },
    sideEffects: ["Ankle swelling", "Flushing", "Headache", "Dizziness", "Fatigue"],
    longTermEffects: ["Gum overgrowth", "Peripheral edema"],
    contraindications: ["Severe hypotension", "Cardiogenic shock", "Unstable angina"],
    foodInteractions: ["Avoid grapefruit juice — increases drug levels"],
    drugInteractions: ["Simvastatin (reduce statin dose)", "Cyclosporine", "Tacrolimus"],
    warnings: ["Never stop suddenly", "Avoid grapefruit juice", "Monitor blood pressure regularly"],
    whoShouldNotTake: ["Severe low blood pressure patients", "Cardiogenic shock patients"],
    foodTiming: "Can be taken with or without food. Avoid grapefruit.",
    pregnancyWarning: "Avoid during pregnancy if possible. Use only if benefit outweighs risk.",
    breastfeedingWarning: "Avoid during breastfeeding.",
    requiresPrescription: true, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Nifedipine", "Diltiazem"],
    aiExplanation: "Amlodipine controls blood pressure and prevents chest pain. Never stop suddenly. Avoid grapefruit juice as it makes the medicine too strong.",
    isEnriched: true,
  },
  {
    name: "Azithromycin", brand: "Various", generic: "Azithromycin", category: "antibiotic",
    description: "Macrolide antibiotic used for respiratory infections, skin infections, and sexually transmitted diseases.",
    dosage: "500mg once daily for 3 days", price: 150, stock: 250,
    dosageGuide: { adult: "500mg on day 1, then 250mg daily for 4 days", child: "10mg/kg on day 1, then 5mg/kg for 4 days", elderly: "Same as adult", notes: "Complete full course" },
    sideEffects: ["Nausea", "Diarrhea", "Stomach pain", "Headache"],
    longTermEffects: ["Heart rhythm problems", "Antibiotic resistance"],
    contraindications: ["Liver disease", "Heart rhythm disorders", "Macrolide allergy"],
    foodInteractions: ["Can be taken with or without food"],
    drugInteractions: ["Warfarin", "Digoxin", "Antacids (take 2 hours apart)"],
    warnings: ["Report chest pain or irregular heartbeat", "Complete full course"],
    whoShouldNotTake: ["Liver disease patients", "Heart rhythm disorder patients"],
    foodTiming: "Can be taken with or without food",
    pregnancyWarning: "Use only if clearly needed. Consult doctor.",
    breastfeedingWarning: "Small amounts pass into breast milk. Use with caution.",
    requiresPrescription: true, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Amoxicillin", "Clarithromycin"],
    aiExplanation: "Azithromycin is an antibiotic that works for 5-7 days even after you finish the 3-day course. Never skip doses and always complete the full course.",
    isEnriched: true,
  },
  {
    name: "Atenolol", brand: "Various", generic: "Atenolol", category: "cardiovascular",
    description: "Beta-blocker used to treat high blood pressure, angina, and irregular heart rhythms.",
    dosage: "50mg once daily", price: 40, stock: 350,
    dosageGuide: { adult: "50-100mg once daily", child: "0.5-1mg/kg daily", elderly: "Start with 25mg daily", notes: "Take at same time each day" },
    sideEffects: ["Fatigue", "Cold hands and feet", "Slow heart rate", "Dizziness", "Depression"],
    longTermEffects: ["Masking of hypoglycemia symptoms in diabetics"],
    contraindications: ["Asthma", "Severe bradycardia", "Cardiogenic shock", "Heart block"],
    foodInteractions: ["Avoid alcohol"],
    drugInteractions: ["Calcium channel blockers", "Digoxin", "Clonidine", "NSAIDs"],
    warnings: ["Never stop suddenly — can cause heart attack", "Avoid in asthma patients"],
    whoShouldNotTake: ["Asthma patients", "Severe slow heart rate patients"],
    foodTiming: "Can be taken with or without food. Take at same time daily.",
    pregnancyWarning: "Can cause fetal growth restriction. Use with caution under supervision.",
    breastfeedingWarning: "Small amounts pass into breast milk. Monitor infant for slow heart rate.",
    requiresPrescription: true, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Amlodipine", "Lisinopril"],
    aiExplanation: "Atenolol slows your heart and lowers blood pressure. Never stop suddenly as it can cause a heart attack. Avoid if you have asthma.",
    isEnriched: true,
  },
  {
    name: "Calpol", brand: "GSK", generic: "Paracetamol", category: "painkiller",
    description: "Children's paracetamol suspension for fever and mild pain relief in infants and children.",
    dosage: "120mg/5ml suspension", price: 55, stock: 300,
    dosageGuide: { adult: "Not for adults", child: "3 months-1 year: 2.5ml, 1-5 years: 5ml, 6-12 years: 10ml every 4-6 hours", elderly: "Not applicable", notes: "Max 4 doses in 24 hours" },
    sideEffects: ["Rare: liver damage with overdose", "Allergic reactions"],
    longTermEffects: ["Liver damage with prolonged overdose"],
    contraindications: ["Under 3 months unless directed by doctor", "Liver disease"],
    foodInteractions: ["Can be given with or without food"],
    drugInteractions: ["Other paracetamol products", "Warfarin"],
    warnings: ["Do not give with other paracetamol products", "Check dose carefully by weight"],
    whoShouldNotTake: ["Infants under 3 months", "Children with liver disease"],
    foodTiming: "Can be given with or without food",
    pregnancyWarning: "Not applicable — children's medicine",
    breastfeedingWarning: "Not applicable — children's medicine",
    requiresPrescription: false, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Panadol Syrup", "Nurofen for Children"],
    aiExplanation: "Calpol is a liquid paracetamol for children. Always measure the correct dose by your child's weight or age. Never give more than 4 doses in 24 hours.",
    isEnriched: true,
  },
  {
    name: "Ponstan", brand: "Pfizer", generic: "Mefenamic Acid", category: "painkiller",
    description: "Anti-inflammatory painkiller used for menstrual pain, dental pain, headaches, and mild to moderate pain.",
    dosage: "500mg three times daily", price: 65, stock: 300,
    dosageGuide: { adult: "500mg three times daily after food", child: "Not recommended under 14", elderly: "Use with caution", notes: "Always take with food" },
    sideEffects: ["Stomach upset", "Diarrhea", "Nausea", "Drowsiness", "Rash"],
    longTermEffects: ["Kidney damage", "Stomach ulcers", "Cardiovascular risk"],
    contraindications: ["Peptic ulcer", "Kidney disease", "Inflammatory bowel disease", "Under 14"],
    foodInteractions: ["Must be taken with food", "Avoid alcohol"],
    drugInteractions: ["Warfarin", "Aspirin", "ACE inhibitors", "Diuretics"],
    warnings: ["Always take with food", "Do not take for more than 7 days without doctor advice"],
    whoShouldNotTake: ["Stomach ulcer patients", "Kidney disease patients", "Under 14"],
    foodTiming: "Must be taken immediately after food",
    pregnancyWarning: "Avoid during pregnancy especially in third trimester.",
    breastfeedingWarning: "Avoid during breastfeeding.",
    requiresPrescription: false, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Panadol", "Brufen"],
    aiExplanation: "Ponstan relieves period pain and other pain. Always take with food to protect your stomach. Don't use for more than 7 days without seeing a doctor.",
    isEnriched: true,
  },
  {
    name: "Zyrtec", brand: "UCB", generic: "Cetirizine", category: "antihistamine",
    description: "Antihistamine used to relieve allergy symptoms including hay fever, hives, and allergic rhinitis.",
    dosage: "10mg once daily", price: 35, stock: 400,
    dosageGuide: { adult: "10mg once daily", child: "6-12 years: 5mg twice daily", elderly: "5mg once daily", notes: "Can be taken at night to avoid daytime drowsiness" },
    sideEffects: ["Drowsiness", "Dry mouth", "Headache", "Dizziness", "Fatigue"],
    longTermEffects: ["Tolerance may develop"],
    contraindications: ["Severe kidney disease", "Cetirizine allergy"],
    foodInteractions: ["Avoid alcohol — increases drowsiness"],
    drugInteractions: ["Alcohol", "Sedatives", "Anxiolytics"],
    warnings: ["May cause drowsiness — avoid driving", "Avoid alcohol"],
    whoShouldNotTake: ["Severe kidney disease patients"],
    foodTiming: "Can be taken with or without food. Best taken at night.",
    pregnancyWarning: "Use only if clearly necessary. Consult doctor.",
    breastfeedingWarning: "Avoid during breastfeeding.",
    requiresPrescription: false, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Loratadine", "Fexofenadine"],
    aiExplanation: "Zyrtec relieves allergy symptoms like sneezing and itching. It may cause drowsiness so it's best taken at night. Avoid driving after taking it.",
    isEnriched: true,
  },
  {
    name: "Glucophage", brand: "Merck", generic: "Metformin", category: "diabetes",
    description: "Brand name Metformin used to control blood sugar in type 2 diabetes.",
    dosage: "500mg twice daily with meals", price: 90, stock: 350,
    dosageGuide: { adult: "500mg twice daily with meals, max 2550mg/day", child: "10+ years: 500mg twice daily", elderly: "Use with caution, monitor kidneys", notes: "Never take on empty stomach" },
    sideEffects: ["Nausea", "Diarrhea", "Stomach pain", "Metallic taste"],
    longTermEffects: ["Vitamin B12 deficiency", "Lactic acidosis (rare)"],
    contraindications: ["Kidney disease (eGFR <30)", "Liver disease", "Heart failure"],
    foodInteractions: ["Always take with meals"],
    drugInteractions: ["Contrast dyes", "Alcohol", "Diuretics"],
    warnings: ["Stop before surgery or contrast procedures", "Monitor kidney function"],
    whoShouldNotTake: ["Kidney disease patients", "Liver disease patients"],
    foodTiming: "Always take with meals to reduce stomach side effects",
    pregnancyWarning: "Not recommended. Insulin preferred during pregnancy.",
    breastfeedingWarning: "Consult doctor before use.",
    requiresPrescription: true, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Metformin generic", "Sitagliptin"],
    aiExplanation: "Glucophage is Metformin for diabetes control. Always take with food. Never stop without doctor's advice as it helps keep your blood sugar stable.",
    isEnriched: true,
  },
  {
    name: "Risek", brand: "Getz Pharma", generic: "Omeprazole", category: "antacid",
    description: "Pakistani brand of Omeprazole. Reduces stomach acid for treatment of ulcers, acid reflux, and GERD.",
    dosage: "20mg once daily before breakfast", price: 95, stock: 400,
    dosageGuide: { adult: "20-40mg once daily before breakfast", child: "0.5-1mg/kg once daily", elderly: "Same as adult", notes: "Take 30 minutes before breakfast" },
    sideEffects: ["Headache", "Diarrhea", "Nausea", "Stomach pain", "Flatulence"],
    longTermEffects: ["Magnesium deficiency", "Vitamin B12 deficiency", "Bone fractures"],
    contraindications: ["Omeprazole allergy"],
    foodInteractions: ["Take before meals"],
    drugInteractions: ["Clopidogrel", "Methotrexate", "Digoxin"],
    warnings: ["Do not use long-term without supervision", "May mask stomach cancer symptoms"],
    whoShouldNotTake: ["Patients on clopidogrel"],
    foodTiming: "Take 30 minutes before breakfast on empty stomach",
    pregnancyWarning: "Use with caution. Only if necessary.",
    breastfeedingWarning: "Avoid if possible.",
    requiresPrescription: false, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Pantoprazole", "Nexium"],
    aiExplanation: "Risek reduces stomach acid and treats acidity and ulcers. Take it 30 minutes before breakfast. Don't use for more than 2 weeks without a doctor's advice.",
    isEnriched: true,
  },
  {
    name: "Septran", brand: "GSK", generic: "Co-trimoxazole", category: "antibiotic",
    description: "Combination antibiotic (Sulfamethoxazole + Trimethoprim) for urinary tract infections, respiratory infections, and traveler's diarrhea.",
    dosage: "960mg twice daily", price: 55, stock: 250,
    dosageGuide: { adult: "960mg (2 tablets) twice daily for 5-7 days", child: "24mg/kg/day in 2 divided doses", elderly: "Same as adult with kidney monitoring", notes: "Drink plenty of water" },
    sideEffects: ["Nausea", "Vomiting", "Skin rash", "Sun sensitivity"],
    longTermEffects: ["Kidney damage", "Bone marrow suppression"],
    contraindications: ["Sulfa allergy", "Severe kidney or liver disease", "Pregnancy at term"],
    foodInteractions: ["Take with food", "Drink 8 glasses of water daily"],
    drugInteractions: ["Warfarin", "Methotrexate", "ACE inhibitors", "Oral contraceptives"],
    warnings: ["Drink plenty of water", "Avoid prolonged sun exposure", "Check for sulfa allergy"],
    whoShouldNotTake: ["Sulfa allergy patients", "Severe kidney disease patients", "Newborns"],
    foodTiming: "Take with food and plenty of water",
    pregnancyWarning: "Avoid in first trimester and near term delivery.",
    breastfeedingWarning: "Avoid during breastfeeding, especially with premature or jaundiced infants.",
    requiresPrescription: true, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Ciprofloxacin", "Amoxicillin"],
    aiExplanation: "Septran is an antibiotic for UTIs and respiratory infections. Drink lots of water when taking it to protect your kidneys. Check if you are allergic to sulfa drugs.",
    isEnriched: true,
  },
  {
    name: "Alprazolam", brand: "Various", generic: "Alprazolam", category: "psychiatric",
    description: "Benzodiazepine used for anxiety disorders and panic disorder. Highly addictive — should only be used short-term.",
    dosage: "0.25-0.5mg three times daily", price: 40, stock: 100,
    dosageGuide: { adult: "0.25-0.5mg three times daily, max 4mg/day", child: "Not recommended under 18", elderly: "0.25mg twice daily", notes: "Use for shortest possible time" },
    sideEffects: ["Drowsiness", "Dizziness", "Memory problems", "Coordination problems", "Dependence"],
    longTermEffects: ["Addiction", "Memory impairment", "Depression", "Severe withdrawal symptoms"],
    contraindications: ["Respiratory disease", "Sleep apnea", "Liver disease", "Pregnancy"],
    foodInteractions: ["Avoid alcohol — DANGEROUS combination", "Avoid grapefruit juice"],
    drugInteractions: ["Alcohol (DANGEROUS)", "Opioids (DANGEROUS)", "Other sedatives", "Antifungals"],
    warnings: ["HIGHLY ADDICTIVE — use only as prescribed", "Never stop suddenly", "Never combine with alcohol"],
    whoShouldNotTake: ["Pregnant women", "Respiratory disease patients", "Alcohol or drug users", "Under 18"],
    foodTiming: "Can be taken with or without food. Avoid alcohol completely.",
    pregnancyWarning: "CONTRAINDICATED during pregnancy. Causes birth defects and neonatal withdrawal.",
    breastfeedingWarning: "CONTRAINDICATED during breastfeeding.",
    requiresPrescription: true, isCommonlyMisused: true, isApproved: true,
    safeAlternatives: ["Buspirone", "SSRIs for anxiety"],
    aiExplanation: "Alprazolam (Xanax) is for anxiety but is HIGHLY addictive. It is one of the most misused medicines in Pakistan. Never take without strict medical supervision and never combine with alcohol.",
    isEnriched: true,
  },
  {
    name: "Voltaren", brand: "Novartis", generic: "Diclofenac", category: "painkiller",
    description: "Anti-inflammatory painkiller used for arthritis, back pain, menstrual pain, and other inflammatory conditions.",
    dosage: "50mg three times daily", price: 75, stock: 300,
    dosageGuide: { adult: "50mg three times daily or 75mg twice daily", child: "1-3mg/kg daily in divided doses", elderly: "Use lowest effective dose", notes: "Always take with food" },
    sideEffects: ["Stomach pain", "Nausea", "Diarrhea", "Headache", "Dizziness"],
    longTermEffects: ["Stomach ulcers", "Cardiovascular risk", "Kidney damage"],
    contraindications: ["Peptic ulcer", "Severe heart failure", "Severe kidney disease", "Asthma triggered by NSAIDs"],
    foodInteractions: ["Must take with food", "Avoid alcohol"],
    drugInteractions: ["Warfarin", "Aspirin", "Methotrexate", "Lithium", "ACE inhibitors"],
    warnings: ["Take with food", "Avoid in heart disease", "Monitor blood pressure"],
    whoShouldNotTake: ["Stomach ulcer patients", "Heart disease patients", "Severe kidney patients"],
    foodTiming: "Must be taken with food or milk",
    pregnancyWarning: "Avoid in third trimester. Use with caution in earlier stages.",
    breastfeedingWarning: "Small amounts pass into breast milk. Use with caution.",
    requiresPrescription: false, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Panadol", "Brufen"],
    aiExplanation: "Voltaren reduces inflammation and pain. Always take with food to protect your stomach. People with heart problems or stomach ulcers should avoid it.",
    isEnriched: true,
  },
  {
    name: "Lasix", brand: "Sanofi", generic: "Furosemide", category: "cardiovascular",
    description: "Loop diuretic (water pill) used to treat fluid retention in heart failure, kidney disease, and liver disease.",
    dosage: "40mg once daily in the morning", price: 30, stock: 200,
    dosageGuide: { adult: "20-80mg daily in the morning", child: "1-2mg/kg daily", elderly: "Start with lowest dose", notes: "Take in morning to avoid nighttime urination" },
    sideEffects: ["Frequent urination", "Dizziness", "Low blood pressure", "Electrolyte imbalance", "Dehydration"],
    longTermEffects: ["Potassium deficiency", "Hearing loss (high doses)", "Gout"],
    contraindications: ["Anuria", "Severe electrolyte depletion", "Sulfa allergy"],
    foodInteractions: ["Avoid excess salt", "Eat potassium-rich foods (bananas, oranges)"],
    drugInteractions: ["Digoxin", "ACE inhibitors", "Aminoglycosides", "NSAIDs"],
    warnings: ["Monitor electrolytes", "Take in morning", "Stay hydrated", "Eat potassium-rich foods"],
    whoShouldNotTake: ["Patients with no urine production", "Severe electrolyte imbalance patients"],
    foodTiming: "Take in the morning with or without food",
    pregnancyWarning: "Use only if necessary. May affect fetal development.",
    breastfeedingWarning: "May suppress lactation. Avoid if possible.",
    requiresPrescription: true, isCommonlyMisused: false, isApproved: true,
    safeAlternatives: ["Hydrochlorothiazide", "Spironolactone"],
    aiExplanation: "Lasix removes extra fluid from your body. Take it in the morning so you don't need to urinate at night. Eat bananas and oranges to replace potassium lost.",
    isEnriched: true,
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ Connected to MongoDB");

    let added = 0;
    let skipped = 0;

    for (const med of medicines) {
      const exists = await Medicine.findOne({ name: med.name });
      if (exists) {
        console.log(`⏭️  Skipped (already exists): ${med.name}`);
        skipped++;
        continue;
      }
      await Medicine.create({ ...med, createdBy: null });
      console.log(`✅ Added: ${med.name}`);
      added++;
    }

    console.log(`\n🎉 Done! Added: ${added}, Skipped: ${skipped}`);
    process.exit(0);
  } catch (err) {
    console.error("❌ Seed error:", err.message);
    process.exit(1);
  }
};

seed();